apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: journal-app  # 👈 Must match the namespace of your other resources
  labels:
    app: fastapi-app
spec:
  replicas: 2  # 🔁 How many pods you want
  selector:
    matchLabels:
      app: fastapi-app  # 🎯 Match pods with this label
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: bufic/fastapi-app:latest  # 🐳 Your Docker image from Docker Hub
        ports:
        - containerPort: 8000  # 🌐 Port inside container that FastAPI listens on
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: journal-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: journal-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DATABASE_URL
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
