version: "3.8"

services:
  dev:
    # image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    image: journal-api
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
